#---------------------------------------------------------------------
# GitHub Actions to Protect CI/CD Pipelines
#
# Version      Date        Info
# 1.0          2020        Initial Version
#
# Made by Felipe Costa
#---------------------------------------------------------------------

name: AWS-Pipeline

env:
  PACKAGES_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
  SNYK_TOKEN: ${{ secrets.SNYK_API }}
  TREND_AP_KEY: ${{ secrets.TREND_AP_KEY }}
  TREND_AP_SECRET: ${{ secrets.TREND_AP_SECRET }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  DSSC_SMARTCHECK_HOST: ${{ secrets.DSSC_SMARTCHECK_HOST }}
  DSSC_SMARTCHECK_USER: ${{ secrets.DSSC_SMARTCHECK_USER }}
  DSSC_SMARTCHECK_PASSWORD: ${{ secrets.DSSC_SMARTCHECK_PASSWORD }}

on: push
      
jobs:
    Code_Scan:
       runs-on: ubuntu-latest
       steps:
         - name: Checkout repository
           run: echo "Code Scan"
    Dependency_Check:
       runs-on: ubuntu-latest
       needs: [Code_Scan]
       steps:
         - uses: actions/checkout@v2
         - name: Snyk Scan
           run: echo "Snyk Scan"
    Build_and_Push:
        runs-on: ubuntu-latest
        needs: [Dependency_Check]
        steps:
          - uses: actions/checkout@v2
          - name: Container Build
            run : |
              cd django-app && docker build -t django-app:latest .
              cd ../java-app && docker build -t java-app:latest .
              cd ../node-app && docker build -t node-app:latest .
              cd ../dotnet-core-app && docker build -t dotnet-core-app:latest .
          - name: Login to Amazon ECR
            id: login-ecr
            uses: aws-actions/amazon-ecr-login@v1
            env:
              AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
              AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              AWS_REGION: us-east-1
          - name: Tag Docker Image
            run: |
              docker tag django-app 789900764224.dkr.ecr.us-east-1.amazonaws.com/django-app:latest
              docker tag java-app 789900764224.dkr.ecr.us-east-1.amazonaws.com/java-app:latest
              docker tag node-app 789900764224.dkr.ecr.us-east-1.amazonaws.com/node-app:latest
              docker tag dotnet-core-app 789900764224.dkr.ecr.us-east-1.amazonaws.com/dotnet-core-app:latest
          - name: Push Docker Images to ECR
            run: |
              docker push 789900764224.dkr.ecr.us-east-1.amazonaws.com/django-app:latest
              docker push 789900764224.dkr.ecr.us-east-1.amazonaws.com/java-app:latest
              docker push 789900764224.dkr.ecr.us-east-1.amazonaws.com/node-app:latest
              docker push 789900764224.dkr.ecr.us-east-1.amazonaws.com/dotnet-core-app:latest
    Container_Scan:
       runs-on: ubuntu-latest
       needs: [Build_and_Push]
       steps:
         - name: Cloud One Container Scan ECR - Django-app
           uses: felipecosta09/Deep-Security-Smart-Check-Scan-Action@v1.0.2
           with:
              DSSC_IMAGE_NAME: 789900764224.dkr.ecr.us-east-1.amazonaws.com/django-app
              DSSC_SMARTCHECK_HOST: ${{ secrets.DSSC_SMARTCHECK_HOST }}
              DSSC_SMARTCHECK_USER: ${{ secrets.DSSC_SMARTCHECK_USER }}
              DSSC_SMARTCHECK_PASSWORD: ${{ secrets.DSSC_SMARTCHECK_PASSWORD }}
              DSSC_IMAGE_PULL_AUTH: ${{ secrets.AWS_PULL_AUTH }}
              DSSC_FINDINGS_THRESHOLD: '{"malware": 999, "vulnerabilities": { "defcon1": 999, "critical": 999, "high": 999 }, "contents": { "defcon1": 999, "critical": 999, "high": 999 }, "checklists": { "defcon1": 999, "critical": 999, "high": 999 }}'
              DSSC_INSECURE_SKIP_TLS_VERIFY: true
              DSSC_INSECURE_SKIP_REGISTRY_TLS_VERIFY: true
         - name: Cloud One Container Scan ECR - Java App
           uses: felipecosta09/Deep-Security-Smart-Check-Scan-Action@v1.0.2
           with:
              DSSC_IMAGE_NAME: 789900764224.dkr.ecr.us-east-1.amazonaws.com/java-app
              DSSC_SMARTCHECK_HOST: ${{ secrets.DSSC_SMARTCHECK_HOST }}
              DSSC_SMARTCHECK_USER: ${{ secrets.DSSC_SMARTCHECK_USER }}
              DSSC_SMARTCHECK_PASSWORD: ${{ secrets.DSSC_SMARTCHECK_PASSWORD }}
              DSSC_IMAGE_PULL_AUTH: ${{ secrets.AWS_PULL_AUTH }}
              DSSC_FINDINGS_THRESHOLD: '{"malware": 999, "vulnerabilities": { "defcon1": 999, "critical": 999, "high": 999 }, "contents": { "defcon1": 999, "critical": 999, "high": 999 }, "checklists": { "defcon1": 999, "critical": 999, "high": 999 }}'
              DSSC_INSECURE_SKIP_TLS_VERIFY: true
              DSSC_INSECURE_SKIP_REGISTRY_TLS_VERIFY: true
         - name: Cloud One Container Scan ECR - Node App
           uses: felipecosta09/Deep-Security-Smart-Check-Scan-Action@v1.0.2
           with:
              DSSC_IMAGE_NAME: 789900764224.dkr.ecr.us-east-1.amazonaws.com/node-app
              DSSC_SMARTCHECK_HOST: ${{ secrets.DSSC_SMARTCHECK_HOST }}
              DSSC_SMARTCHECK_USER: ${{ secrets.DSSC_SMARTCHECK_USER }}
              DSSC_SMARTCHECK_PASSWORD: ${{ secrets.DSSC_SMARTCHECK_PASSWORD }}
              DSSC_IMAGE_PULL_AUTH: ${{ secrets.AWS_PULL_AUTH }}
              DSSC_FINDINGS_THRESHOLD: '{"malware": 999, "vulnerabilities": { "defcon1": 999, "critical": 999, "high": 999 }, "contents": { "defcon1": 999, "critical": 999, "high": 999 }, "checklists": { "defcon1": 999, "critical": 999, "high": 999 }}'
              DSSC_INSECURE_SKIP_TLS_VERIFY: true
              DSSC_INSECURE_SKIP_REGISTRY_TLS_VERIFY: true
         - name: Cloud One Container Scan ECR - .Net Core App
           uses: felipecosta09/Deep-Security-Smart-Check-Scan-Action@v1.0.2
           with:
              DSSC_IMAGE_NAME: 789900764224.dkr.ecr.us-east-1.amazonaws.com/dotnet-core-app
              DSSC_SMARTCHECK_HOST: ${{ secrets.DSSC_SMARTCHECK_HOST }}
              DSSC_SMARTCHECK_USER: ${{ secrets.DSSC_SMARTCHECK_USER }}
              DSSC_SMARTCHECK_PASSWORD: ${{ secrets.DSSC_SMARTCHECK_PASSWORD }}
              DSSC_IMAGE_PULL_AUTH: ${{ secrets.AWS_PULL_AUTH }}
              DSSC_FINDINGS_THRESHOLD: '{"malware": 999, "vulnerabilities": { "defcon1": 999, "critical": 999, "high": 999 }, "contents": { "defcon1": 999, "critical": 999, "high": 999 }, "checklists": { "defcon1": 999, "critical": 999, "high": 999 }}'
              DSSC_INSECURE_SKIP_TLS_VERIFY: true
              DSSC_INSECURE_SKIP_REGISTRY_TLS_VERIFY: true
         - name: Cointainer Successfully Scanned
           run : echo "CI Pipeline part finished successfully"
    Dev_Tests:
        runs-on: ubuntu-latest
        needs: [Container_Scan]
        steps:
         - name: Dev Tests
           run: echo Dev Tests
      
         - name: Unit Tests
           run: echo Unit Tests
           
         - name: Dev Tests part finished successfully
           run : echo "Dev Tests part finished successfully"
    Deploy:
        runs-on: ubuntu-latest
        needs: [Dev_Tests]
        steps:
         - name: Deploy to AWS
           run: | 
              echo "Deployed"
